DROP EXTERNAL TABLE dbo.DeltaTest;
DROP EXTERNAL TABLE dbo.ParquetTest;
DROP EXTERNAL DATA SOURCE DeltaLakeDataSource;
DROP EXTERNAL FILE FORMAT DeltaLakeFileFormat;
DROP EXTERNAL FILE FORMAT ParquetFileFormat;